name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-json-agg
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v4.6.1
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          pip install --constraint="$(pwd)/.github/workflows/constraints.txt" pip
          pip --version

      - name: Install Poetry
        run: |
          pip install --constraint="$(pwd)/.github/workflows/constraints.txt" poetry
          poetry --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "sha=$(git rev-parse --verify --quiet HEAD^)" >> $GITHUB_OUTPUT

      - name: Check version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        run: |
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Tag new version if it doesn't exist
        id: tag-version
        if: steps.check-version.outputs.version
        uses: butlerlogic/action-autotag@1.1.3 # don't update until https://github.com/ButlerLogic/action-autotag/issues/49 is fixed
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: "${{ steps.check-version.outputs.version }}"

      - name: Bump version for developmental release
        if: "! steps.tag-version.outputs.tagname"
        run: |
          poetry version patch &&
          version=$(poetry version -s) &&
          poetry version $version.dev.$(date +%s)

      - name: Build package
        run: |
          poetry build --ansi

      - name: Publish package on PyPI
        if: steps.tag-version.outputs.tagname
        uses: pypa/gh-action-pypi-publish@v1.9.0

      - name: Publish package on TestPyPI
        if: "! steps.tag-version.outputs.tagname"
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v6.0.0
        with:
          publish: ${{ steps.tag-version.outputs.tagname != '' }}
          tag: ${{ steps.tag-version.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
